// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Server.Data;

#nullable disable

namespace TestTestServer.Migrations
{
    [DbContext(typeof(APIData))]
    partial class APIDataModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Server.Model.Weather", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AdID"));

                    b.Property<string>("Temp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Humidity")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Pressure")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Time")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Predict")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("weather");
                });

            modelBuilder.Entity("Server.Model.Weather", b =>
            {
                b.Property<int>("ID")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AdID"));

                b.Property<string>("Temp")
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("Humidity")
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("Pressure")
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("Time")
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("Predict")
                    .HasColumnType("nvarchar(max)");

                b.HasKey("ID");

                b.ToTable("weatherShow");
            });
#pragma warning restore 612, 618
        }
    }
}
